[tool.poetry]
name = "chispa"
version = "0.10.0"
description = "Pyspark test helper library"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.2"
pyspark = ">3.0.0"
findspark = "1.4.2"
pytest-describe = "^2.1.0"

[tool.poetry.group.mkdocs.dependencies]
mkdocstrings-python = "^1.7.3"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"
markdown-include = "^0.8.1"
mkdocs = "^1.5.3"

[tool.poetry.group.mkdocs]
optional = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
