[tool.poetry]
name = "chispa"
version = "0.2.1"
description = "Pyspark test helper library"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pyspark = "^2.0.0"
PrettyTable = "^0.7.2"

[tool.poetry.dev-dependencies]
pytest = "3.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
