[tool.poetry]
name = "chispa"
version = "0.2.0"
description = "Pyspark test helper library"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pytest = "3.2.2"
pyspark = "2.4.0"

[tool.poetry.dev-dependencies]
pytest = "3.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
