[tool.poetry]
name = "chispa"
version = "0.5.0"
description = "Pyspark test helper library"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">2.7"
pyspark = ">2.0.0"

[tool.poetry.dev-dependencies]
pytest = "3.2.2"
pytest_describe = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
